schema = 3

[mod]
  [mod."github.com/BurntSushi/freetype-go"]
    version = "v0.0.0-20160129220410-b763ddbfe298"
    hash = "sha256-jnKLDuMZFUN5GqtDj72rU5pHu0/fw9ksyo1nocFW74g="
  [mod."github.com/BurntSushi/graphics-go"]
    version = "v0.0.0-20160129215708-b43f31a4a966"
    hash = "sha256-Fg4aoXHAzets4D6oPMydiNf3BUQCTpo0ItLQIvPkBIE="
  [mod."github.com/Luzifer/go_helpers"]
    version = "v2.8.1+incompatible"
    hash = "sha256-p9cYnxghTBlU0AhV49pTeYWAzpXLH52aBajMlydNfGM="
  [mod."github.com/Luzifer/go_helpers/v2"]
    version = "v2.10.0"
    hash = "sha256-m1OCpPL9y3wDx6SaUd+O2g3lW/qkL6WnVA1EalwB2r0="
  [mod."github.com/Luzifer/rconfig"]
    version = "v2.2.0+incompatible"
    hash = "sha256-rCelahWtReYNNCWOHRL9M5gBWNxy+uObO9zNS5ITIzQ="
  [mod."github.com/Luzifer/rconfig/v2"]
    version = "v2.2.1"
    hash = "sha256-f8D2V9Emq1FGVu1/T59PK1Mska5EVJp2DF1e85m1WlQ="
  [mod."github.com/Luzifer/streamdeck"]
    version = "v1.7.0"
    hash = "sha256-YZOOsqxvRVzMB1F06oP3uoQ6Lz21xhxJV/9IVylsuP4="
  [mod."github.com/chzyer/logex"]
    version = "v1.1.10"
    hash = "sha256-BNOaV/CFAqOymWW3R2m1sCikdCwFZM/pVkylzoeU6yI="
  [mod."github.com/chzyer/readline"]
    version = "v0.0.0-20180603132655-2972be24d48e"
    hash = "sha256-2Uj5LGpHEbLQG3d/7z9AL8DknUBZyoTAMs4j+VVDmIA="
  [mod."github.com/chzyer/test"]
    version = "v0.0.0-20180213035817-a1ea475d72b1"
    hash = "sha256-U0irpUSqegh7Nzg1ErPuyjESOcIXXOWf7ikKMbES2mY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/disintegration/imaging"]
    version = "v1.6.2"
    hash = "sha256-pSeMTPvSkxlthh65LjNYYhPLvCZDkBgVgAGYWW0Aguo="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.9"
    hash = "sha256-HZBMhbFqcZM9oxSbWqISzEE7GF7JZpco5tyta6c4OcQ="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.3"
    hash = "sha256-2L7k6GfrcW3GXXYr1FYIu20aZBjIF0cTKdte6D4riH8="
  [mod."github.com/go-task/slim-sprig"]
    version = "v0.0.0-20210107165309-348f09dbbbc0"
    hash = "sha256-jgza4peLzeJlwmMh/c1gNkmtwA9YtSdGaBzBUDXhIZo="
  [mod."github.com/golang/freetype"]
    version = "v0.0.0-20170609003504-e2365dfdc4a0"
    hash = "sha256-AHAFBd20/tqxohkWyQkui2bUef9i1HWYgk9LOIFErvA="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20210407192527-94a9f03dee38"
    hash = "sha256-ryvI75ePFCfy0qvAhEFbtB/c/Er7nvLwm7CVASBRhsI="
  [mod."github.com/hpcloud/tail"]
    version = "v1.0.0"
    hash = "sha256-7ByBr/RcOwIsGPCiCUpfNwUSvU18QAY+HMnCJr8uU1w="
  [mod."github.com/ianlancetaylor/demangle"]
    version = "v0.0.0-20200824232613-28f6c0f3b639"
    hash = "sha256-A+Wg+8KOpMZfhAKyOFIK79fcdYuKHRp6cIC0J4QZWGc="
  [mod."github.com/inconshreveable/go-update"]
    version = "v0.0.0-20160112193335-8152e7eb6ccf"
    hash = "sha256-Izbcv7BuWoBECFU/bzegBRJXWTKmZgIAVSfeqa6Gnx0="
  [mod."github.com/jezek/xgb"]
    version = "v1.1.0"
    hash = "sha256-qLbiTgZp/b+4+2LRXgdQRl8B1QsfiGteuNoGBQkI5rI="
  [mod."github.com/jezek/xgbutil"]
    version = "v0.0.0-20230205170612-7a8cf053cf43"
    hash = "sha256-DcjgRqb9CtsFl+l7CaWomZEs7mKQRzjvbl7ZltYakJk="
  [mod."github.com/jfreymuth/pulse"]
    version = "v0.0.0-20200804114219-7d61c4938214"
    hash = "sha256-nESzjsEXAKzFr6fXzIjxjsvibFPoRhVUHyZMfzJ9IXU="
  [mod."github.com/konsorten/go-windows-terminal-sequences"]
    version = "v1.0.2"
    hash = "sha256-p1sYnDuTd1y3pOq1KNPg2LqCWxhduH6Qj+yoGRMQtiY="
  [mod."github.com/leekchan/gtf"]
    version = "v0.0.0-20190214083521-5fba33c5b00b"
    hash = "sha256-RzRO58s1n+uRdGsE5Tz6+AvV2AuY6y4KHH4cACSk0ts="
  [mod."github.com/nfnt/resize"]
    version = "v0.0.0-20180221191011-83c6a9932646"
    hash = "sha256-yvPV+HlDOyJsiwAcVHQkmtw8DHSXyw+cXHkigXm8rAA="
  [mod."github.com/nxadm/tail"]
    version = "v1.4.8"
    hash = "sha256-JP3RZVZLFhaBZ2VdF/fbyMPMLqrPZDjP98f1ey2OePo="
  [mod."github.com/onsi/ginkgo"]
    version = "v1.16.5"
    hash = "sha256-Q3CKWQyIJKOiX9cs4t5Nz4pYxj6CT3AWnMXRNiM71GQ="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.9.1"
    hash = "sha256-7yMsN5CMJS/4VU9/Z27/xdbKzZac6/R1JRJDXxGmwiQ="
  [mod."github.com/onsi/gomega"]
    version = "v1.27.4"
    hash = "sha256-Fhltm/e6KVXdwfUl65cE8PD1MLyXJa7OH0lg4Bvewv0="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/sashko/go-uinput"]
    version = "v0.0.0-20180923134002-15fcac7aa54a"
    hash = "sha256-sL4sy56o6vMRrfZEqU6vrJEsqaJVjOAbfd/9yigxDt0="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.4.2"
    hash = "sha256-3QzWUsapCmg3F7JqUuINT3/UG097uzLff6iCcCgQ43o="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/sstallion/go-hid"]
    version = "v0.13.3"
    hash = "sha256-G2Va80tIMF6cHcxxCsAvx0xSKQ4qKpf2fUB/H8zL6AU="
  [mod."github.com/sstallion/go-tools"]
    version = "v1.0.0"
    hash = "sha256-jOP88ZGjPSaRvxmZSy3VWysi8Nf10XvDwGcLPgzP6R0="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.1"
    hash = "sha256-HdGVZCuy7VprC5W9UxGbDmXqsKADMjpEDht7ilGVLco="
  [mod."github.com/stretchr/testify"]
    version = "v1.5.1"
    hash = "sha256-yatHRznSUGWMn3LkjBYWy2tpi3zNTaojsM+i4IPfZak="
  [mod."github.com/yuin/goldmark"]
    version = "v1.4.13"
    hash = "sha256-GVwFKZY6moIS6I0ZGuio/WtDif+lkZRfqWS6b4AAJyI="
  [mod."golang.org/x/crypto"]
    version = "v0.1.0"
    hash = "sha256-0oZWBSiW5Pd/2a1p2beuoelDe0CpfXZhrg/qPduJlYs="
  [mod."golang.org/x/image"]
    version = "v0.6.0"
    hash = "sha256-fZc2Jfh6EqsjmMBUMaGHn8+bSMetuZ7K4AxU8BRXt94="
  [mod."golang.org/x/mod"]
    version = "v0.9.0"
    hash = "sha256-Lk+O2L4cTlie5j6iO5P3jrkYe2u94Y/a1OFjOBbivIE="
  [mod."golang.org/x/net"]
    version = "v0.8.0"
    hash = "sha256-2cOtqa7aJ5mn64kZ+8+PVjJ4uGbhpXTpC1vm/+iaZzM="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.6.0"
    hash = "sha256-zAgxiTuL24sGhbXrna9R1UYqLQh46ldztpumOScmduY="
  [mod."golang.org/x/term"]
    version = "v0.6.0"
    hash = "sha256-Ao0yXpwY8GyG+/23dVfJUYrfEfNUTES3RF45v1VhUAk="
  [mod."golang.org/x/text"]
    version = "v0.8.0"
    hash = "sha256-hgWFnT01DRmywBEXKYEVaOee7i6z8Ydz7zGbjcWwOgI="
  [mod."golang.org/x/tools"]
    version = "v0.7.0"
    hash = "sha256-ZEjfFulQd6U9r4mEJ5RZOnW49NZnQnrCFLMKCgLg7go="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.0"
    hash = "sha256-p1cVM3OeEErh1WeNRAg4n3zYm/0qPTPmIiWNjRmJiMQ="
  [mod."gopkg.in/check.v1"]
    version = "v0.0.0-20161208181325-20d25e280405"
    hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="
  [mod."gopkg.in/fsnotify.v1"]
    version = "v1.4.7"
    hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="
  [mod."gopkg.in/tomb.v1"]
    version = "v1.0.0-20141024135613-dd632973f1e7"
    hash = "sha256-W/4wBAvuaBFHhowB67SZZfXCRDp5tzbYG4vo81TAFdM="
  [mod."gopkg.in/validator.v2"]
    version = "v2.0.0-20191107172027-c3144fdedc21"
    hash = "sha256-0i8Ye2rLyFUGwxIRzejQs9hZDqLbsdn1zCy8hOQz/BQ="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
